### ISSUE TITLE
Asset Editor support

### ISSUE THREAD

**Issue by Monniasza** [MacSergey/NodeMarkup#105]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  
Assets and UI

#### Describe your idea clearly and concisely.  
Asset Editor support would be used to create both realistic and lightweight intersections on the Workshop.
UI would stay the same, but will be available in Asset Editor too. The process of saving and loading data would be very similar to what TM:PE will use in v1.16.0, but it will store intersection markings instead of traffic management data. 

#### Screenshots?  
Coming soon

#### Why would this idea be a good addition to IMT?
Using compatible intersections from the Workshop would allow realistic cities to be built faster.

**Comment by MacSergey** [comment]
@Monniasza available in 1.4
