### ISSUE TITLE
Yield Line

### ISSUE THREAD

**Issue by Skippern** [MacSergey/NodeMarkup#135]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  
Stop line

#### Describe your idea clearly and concisely.  
Yield lines are a line of triangles, instead of the solid line meaning full stop.

#### Screenshots?  
US Pavement Markings (Federal Highway Administration)
https://mutcd.fhwa.dot.gov/services/publications/fhwaop02090/ymarkings_longdesc.htm

#### Why would this idea be a good addition to IMT?
More options from real life make the tool even more awesome

**Comment by MacSergey** [comment]
@Skippern available in 1.4
