### ISSUE TITLE
Preset intersections rules

### ISSUE THREAD

**Issue by DieuAulas** [MacSergey/NodeMarkup#137]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  
Other

#### Describe your idea clearly and concisely.  
It would be good if we can make preset intersections, like when "this kind of road" cross "this kind of road", we have those lines/fillers. We could save an intersection model and apply to the same kinds of intersection, or auto apply everytime we build the same intersection. Would be great for highway exits/entrance who share the same pattern.

#### Screenshots?  
Provide a visual if possible what your idea would look like
  

#### Why would this idea be a good addition to IMT?
We can save a lot of time for basic intersections

**Comment by Allystrya** [comment]
I am not the brains of course by any means.  But Move It is being updated here in the near future to include IMT's markings being able to be imported and exported and it works very well and I would think that would be a much better alternative for intersections than selecting the thousands of different roads there are.  That would be my suggestion.  I just see somehow incorporating "this road and that road" being a horrible experience on any level given the thousands of roads there are.  Just my 2 cents.  Then again I could be horribly wrong.

**Comment by DieuAulas** [comment]
That would be awesome, thanks for answer
