### ISSUE TITLE
After save and reload the markings are not the same (incompatibility with Node Controller mod?)

### ISSUE THREAD

**Issue by gaborposz** [MacSergey/NodeMarkup#144]
**Which IMT are you using?  _Stable, BETA, BETA with Early Access_**
Stable 1.3

**What computer OS are you using? (ex:  Linux (version), MACOS, Windows (version))**
Windows 10 Pro x64

**Describe the bug**
I'm using [IMT 1.3](https://steamcommunity.com/sharedfiles/filedetails/?id=2140418403) together with [Node Controller V2.0 [Beta]](https://steamcommunity.com/sharedfiles/filedetails/?id=2085403475) to make my highway lanes more realistic. They work together great, but if I quit the game, and later reopen my saved city, then the "Corner smoothness" (set in Node Controller) of the junctions is not applied to markings.

**To Reproduce**
1. Set "Corner smoothness" by Node Controller on a highway junction
2. Create markings with IMT
3. Save the game, and quit Cities Skylines
4. Open Cities Skylines, and reload the saved city

**Expected behavior**
The markings look the same as before.

**Screenshots**
Before saving and leaving the game:
![BeforeSave](https://user-images.githubusercontent.com/47426565/93707985-1efca880-fb33-11ea-81b2-84a60e9ca4b1.jpg)

After reloading the saved city:
![AfterRestart](https://user-images.githubusercontent.com/47426565/93707995-2ae86a80-fb33-11ea-8a8e-7412c47e78f0.jpg)

**Additional information**
The markings are restored if I select the junction by Node Controller, because then the "marking points" gets updated. 
The problem can be also in the Node Controller mod, but it's hard to judge, so I started here as the problem is with the markings.
I'm using [TM:PE [Stable]](https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252), not the [Labs] version, but I doubt that it has anything to do with this particular problem.

**Comment by MacSergey** [comment]
Is your simulation on pause? Have you tried pressing play?

**Comment by gaborposz** [comment]
Starting the simulation doesn't help.

But interestingly, if I quit to main menu, and load the saved game again, then it gets fixed.

Seems to be a kind of "initialization order" problem: When IMT is initialized first, then the Node Controller mod's "corner smoothness" is not applied yet, so the markings are still using the original coordinates. But if I load the city again, then the Node Controller mod is the first, thus the markings are placed correctly.

**Comment by gaborposz** [comment]
Closed without resolution? :(

**Comment by MacSergey** [comment]
@gaborposz It's Node Controller problem
