### ISSUE TITLE
Preset line-colors

### ISSUE THREAD

**Issue by dietrichmd** [MacSergey/NodeMarkup#146]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  

Lines
#### Describe your idea clearly and concisely.  
It would be great to have preset colors -- yellow for lines, green for trams, red for busses, etc...

#### Screenshots?  
Provide a visual if possible what your idea would look like
N/A

**Comment by MacSergey** [comment]
This doesn't make sense because there are so many roads and each one has its own color. In addition the color is affected by the using LUT
