### ISSUE TITLE
Ability to curve lines?

### ISSUE THREAD

**Issue by nicnacnic** [MacSergey/NodeMarkup#158]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  
Lines.

#### Describe your idea clearly and concisely.  
Add the ability to adjust the curve of a line if the automatic curving is not sufficient. Kinda like the Move It! mod.

#### Screenshots?  
Provide a visual if possible what your idea would look like
  
![0rctgua8nhu01](https://user-images.githubusercontent.com/39160563/96399361-2e0b6080-119c-11eb-999e-cd2dedb3e006.jpg)
It's possible to create something like this in the game with the PLT mod, but it is very time consuming and uses many props and decals.

#### Why would this idea be a good addition to IMT?
It would make it a lot easier to make highway ramps like the screenshot posted above. No more fiddling with assets or configuring the Prop Line Tool mod!

**Comment by MacSergey** [comment]
Lines follow traffic path. Not need change curves. 
And again: Node Controller mod help you 🙂
