### ISSUE TITLE
Create New Points and Move Existing Points Off The "Grid"

### ISSUE THREAD

**Issue by nicnacnic** [MacSergey/NodeMarkup#159]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  
Points.

#### Describe your idea clearly and concisely.  
Pretty much the ability to create new points, or move existing points off the "grid" instead of just offsetting them in one direction.

#### Screenshots?  
Provide a visual if possible what your idea would look like
  
Old
![Untitled](https://user-images.githubusercontent.com/39160563/96399976-a58dbf80-119d-11eb-9720-04da86132a81.png)
New
![Untitled2](https://user-images.githubusercontent.com/39160563/96400803-b63f3500-119f-11eb-8dc9-76689ae20cd2.png)
If new points can be created, I could create something like this, to create a more realistic highway ramp. (It's only a concept)
It is actually possible to create something like this using PLT, but it is hard and very time consuming.

#### Why would this idea be a good addition to IMT?
It would be easier to create highway on/off ramps, and do stuff shown in the screenshot above.

**Comment by MacSergey** [comment]
Node Controller mod help you
