### ISSUE TITLE
Allow to work on segments

### ISSUE THREAD

**Issue by DJ-DJL** [MacSergey/NodeMarkup#184]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  
All

#### Describe your idea clearly and concisely.  
It would be nice if we could use this tool on segments too.
Could be particularly useful when we have 2 nodes very close together, both with markings and we want to fill in the gap

#### Screenshots?  
Provide a visual if possible what your idea would look like
  
![image](https://user-images.githubusercontent.com/24252682/98708912-fe5a0d80-2381-11eb-8d82-2cdea6986e2f.png)
![image](https://user-images.githubusercontent.com/24252682/98709125-41b47c00-2382-11eb-9110-86b6d26cd2a7.png)

#### Why would this idea be a good addition to IMT?

Complete the aesthetics for complex junctions.

**Comment by MacSergey** [comment]
This will be in future versions

**Comment by krzychu124** [comment]
> This will be in future versions

This or next year? 🙃

**Comment by MacSergey** [comment]
> > This will be in future versions
> 
> 
> 
> This or next year? 🙃 

It is secret 🙃
