### ISSUE TITLE
Entire intersection templates

### ISSUE THREAD

**Issue by JaffParker** [MacSergey/NodeMarkup#208]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  

Templates

#### Describe your idea clearly and concisely.  

Right now we can create templates of individual lines/fillers. But when you have tons of intersections in a city, it can get cumbersome to create lines and fillers and apply templates for each of them. Is it possible with the IMT to create intersection templates? Could be with very strict rules. For example, a 4-way intersection template created from 2 small roads with trees can only be applied on 4-way intersection of small roads with trees.

#### Screenshots?  

Not sure how to make screenshots of this 

#### Why would this idea be a good addition to IMT?

Creating intersection markings would then become much easier and more appealing. Personally, I only bother with large prominent intersections right now just because the process is more manual than I'd like. By the time I finish one intersection, the city moved on without me lol

**Comment by MacSergey** [comment]
Use presets

**Comment by JaffParker** [comment]
Right. I'm either blind or stupid lol. You can close this
