### ISSUE TITLE
How do you actually use "Split into two"?

### ISSUE THREAD

**Issue by Azzurite** [MacSergey/NodeMarkup#263]
I've split a point into two, wanting to continue each individual line of a double line into a different direction. However, I can't actually select any of the two points to create a new line?

The interface looks like this: 
![grafik](https://user-images.githubusercontent.com/2777158/123155139-03c71c80-d468-11eb-92aa-ad2ba4fd3abb.png)
I can only create a new line at the big center point, not at any of the two split points.

I then tried to go into the line UI and change the rule's "From" point: 
![grafik](https://user-images.githubusercontent.com/2777158/123155267-2fe29d80-d468-11eb-84ef-18396b5a7e38.png)
That makes the 2 split points disappear and only shows me the main one again.

So yeah, how do I actually continue the 2 split lines in different directions?

**Comment by MacSergey** [comment]
You should choose alignment for line that start from this point![image](https://user-images.githubusercontent.com/20316130/123159646-ec8f2b80-d475-11eb-8ad2-cbff23b22103.png)

**Comment by Azzurite** [comment]
Yeah this didn't register at all for me! 

Thanks a lot! Amazing mods you're making.
