### ISSUE TITLE
Saving to assets does not work

### ISSUE THREAD

**Issue by Yuan-9** [MacSergey/NodeMarkup#287]
**Which IMT are you using?  _Stable, BETA, BETA with Early Access_**
stable
**What computer OS are you using? (ex:  Linux (version), MACOS, Windows (version))**
windows

**Describe the bug**
I don't know how to save and publish imt's assets.Nothing happens when I click the Save to Asset button.

**To Reproduce**
1. Go to --Preset
2. Click on --Save to asset

**Expected behavior**
I can see and publish my assets

**Screenshots**
Add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/57804656/134202618-515a0a31-e649-4a5c-8dbd-4efa42b5b6b5.png)

**Additional information**
Add any other relevant information pertaining to the issue goes here.

**Comment by MacSergey** [comment]
Error was fixed in version 1.8.2.1
