### ISSUE TITLE
Zigzag lines

### ISSUE THREAD

**Issue by seanjeromelh** [MacSergey/NodeMarkup#349]
#### Which area of IMT is your request about?  _(ex:  Lines, Fillers, UI)_  

Lines

#### Describe your idea clearly and concisely.  

Continuous zigzag lines
Double Continuous zigzag lines
Broken zigzag lines
Double broken zigzag lines

#### Screenshots?  
Provide a visual if possible what your idea would look like
  

Continuous zigzag lines
![image](https://user-images.githubusercontent.com/120659412/210207385-70268c0e-cc49-433e-a646-8adeb4be6472.png)

Double continuous zigzag lines
![download](https://user-images.githubusercontent.com/120659412/210207182-649fbb91-42dd-4c8e-bd5f-735e74b54987.jpg)

Broken zigzag lines
![520280](https://user-images.githubusercontent.com/120659412/210207093-354ad389-6b73-4762-bc36-7822a2ebb511.jpg)

#### Why would this idea be a good addition to IMT?

The continuous zigzag lines (single/double) allows for more detailed road markings to notify that this is a no parking/waiting zone, as it is in Singapore and several other countries.

The broken zigzag lines are markings that notify a pedestrian crossing ahead, as in many countries like Singapore, Hong Kong, UK, Thailand, Malaysia etc.
![image](https://user-images.githubusercontent.com/120659412/210207527-ec82be7c-77cc-4824-836c-409bf3b04b10.png)
![image](https://user-images.githubusercontent.com/120659412/210207556-fc977787-0c95-4c0b-b2d8-adf0e9d3db85.png)

Really hope to have them included in the next update soon. Thanks!

**Comment by MacSergey** [comment]
It (not all described options) was already added to the last beta version

**Comment by seanjeromelh** [comment]
Thanks for the update!
