### ISSUE TITLE
Auto tooltip for properties says "Range" instead of "Auto"

### ISSUE THREAD

**Issue by lboyling** [MacSergey/NodeMarkup#351]
There's a minor UI issue when using props or trees as the line style - the tooltip for the step property when you hover over the auto option says "Range" instead of "Auto"

![image](https://user-images.githubusercontent.com/17864398/210393050-2f46c947-b5e6-417c-8ce0-9bc686b9f42b.png)

This looks to be the line where the incorrect localization string is used:
https://github.com/MacSergey/NodeMarkup/blob/4f456a2d35df7e132d449d7cf76a9ce37b12d5fa/NodeMarkup/UI/Property%20panels/StaticRangeProperty.cs#L457

**Comment by MacSergey** [comment]
thanks, fixed
