### ISSUE TITLE
Chevron filler

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#62]
In UK it is common to have a chevron filler, especially on motorways, like so:

![image](https://user-images.githubusercontent.com/1386719/88501775-4ec08180-cfc4-11ea-9f39-7fa75c8bd98a.png)

The chevron 'arrows' aligned with traffic - either pointing towards or away from the flow of traffic depending on whether it's an entry or exit slip road. A simple checkbox to toggle direction would suffice to handle the chevron direction.

Would be awesome if those could be added as a fill style :)

**Comment by MacSergey** [comment]
I will do this in the next version
