### ISSUE TITLE
Fill spacing from line not quite right for double/single line mix

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#63]
Example:

![image](https://user-images.githubusercontent.com/1386719/88502006-1cfbea80-cfc5-11ea-85aa-b202d3b8890a.png)

The spacing between the white dashed line is bigger than the spacing between the yellow double line. It's only a minor detail but thought I'd mention it just in case nobody else reported it.

The fill pattern in image above is rotated by +/- 45 degrees.

Also I had some issues trying to get the green stripes (fill) to align with the white dashed line. I can set distance from median but it's always one "line pixel" out.

**Comment by MacSergey** [comment]
the offset is calculated from the center of the line. for a double line it is located between the lines

**Comment by aubergine10** [comment]
I think it's the double where the issue happens. It would be better if it could work out which of the lines in the 'double line' is closest to fill and offset against that instead of the middle of the 2 lines in the 'double line'?

**Comment by MacSergey** [comment]
At the time of calculating the filler, it is not known what style the line has, but only its Bezier curve. I don't see the point in such a complication because of such a small thing

**Comment by aubergine10** [comment]
It is a small thing, however as the whole purpose of the mod is the visual aspect of road markings I think it would be beneficial to try and get them as 'pixel perfect' as possible. The more accurate the lane markings the better it will look.
