### ISSUE TITLE
Corner chevrons (for want of better description)

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#64]
Is there any way to get this sort of effect?

![image](https://user-images.githubusercontent.com/1386719/88502250-c3e08680-cfc5-11ea-940b-d9f5b5a46171.png)

**Comment by MacSergey** [comment]
traffic will cross them

**Comment by aubergine10** [comment]
I found a way to create these:

![image](https://user-images.githubusercontent.com/1386719/88526427-d376c400-cff3-11ea-9b9e-ac66f57a2468.png)

With the lines shown:

![image](https://user-images.githubusercontent.com/1386719/88526556-fd2feb00-cff3-11ea-99a6-ce0a5eb60e5a.png)

Yes. traffic will cross over it, but it is mostly just visual thing. In real life traffic can and often does drive over those things hehe.
