### ISSUE TITLE
Double dashed/solid 'stop lines'

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#65]
In UK it is very common to have double dashed stop line (ie. a "give way" marking):

![image](https://user-images.githubusercontent.com/1386719/88502434-4e28ea80-cfc6-11ea-85aa-66baa7780a35.png)

There are also some rare cases where a double solid stop line is used, eg. at the end of a parking lane or loading bay (usually its single, but not always).

**Comment by aubergine10** [comment]
An example of where I'd want to use double dashed lines (I used a decal instead but it's often difficult to find decal the right size for a given lane width):

![image](https://user-images.githubusercontent.com/1386719/88503095-99dc9380-cfc8-11ea-98e6-7d5fdc4e1f08.png)

**Comment by MacSergey** [comment]
OK, I'll add it

**Comment by aubergine10** [comment]
Just saw these in the update - works great!! 👍 

![image](https://user-images.githubusercontent.com/1386719/88926675-3a9fad00-d26e-11ea-9ce9-2cd980104c69.png)
