### ISSUE TITLE
Very sharp bends at junctions result in line going on pavement

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#66]
Here is illustration of the problem (I added a double yellow at outer edge of road):

![image](https://user-images.githubusercontent.com/1386719/88502616-e45d1080-cfc6-11ea-901e-36017efd3326.png)

Would it be possible for lines at edge of road to get a bezier drag handle or something similar? So I could manually adjust the bezier curve to get the lines back on to the road surface?

![image](https://user-images.githubusercontent.com/1386719/88502664-13738200-cfc7-11ea-9825-bb1d69ce88f0.png)

**Comment by MacSergey** [comment]
there's a 99% chance I won't do it

**Comment by aubergine10** [comment]
Ok, it is a rare fringe case. I will try altering the segments (insert additional node) to see if that helps and report back tomorrow with results.
