### ISSUE TITLE
Stop line offset from junction option

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#67]
Is it possible to allow stop lines to be offset (+/-) from the junction?

![image](https://user-images.githubusercontent.com/1386719/88503764-9944fc80-cfca-11ea-9ce1-a4e6584100cc.png)

Here I want the solid line to connect to the white dashed line of the parking lane. Currently only way to achieve that is to make stop line thicker, but I would prefer to keep it thin and just offset towards/away from the junction.

**Comment by MacSergey** [comment]
I will consider adding this

**Comment by Almiconto** [comment]
It would also be useful when trying to create these kind of stop lines with different offset:

![image](https://user-images.githubusercontent.com/69425389/89940605-0fc43a00-dc1a-11ea-95dc-aa26525358fc.png)
