### ISSUE TITLE
Ability to offset line start/end positions.

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#71]
Example:

![image](https://user-images.githubusercontent.com/1386719/88584630-d8666280-d049-11ea-9348-e9e3c0e82f9b.png)

There the green/red/yellow lines overlap which looks odd.

Would it be possible to get some way to offset the ends of lines from the 'from' and 'to' points? For example, I might want an offset of 10 at the 'from' point and an offset of 3 at the 'to' point. Alternatively, an option "prevent overlap" which would auto-calculate the offset for each end independently.

This would greatly enhance the visual quality of intersection markings.

**Comment by aubergine10** [comment]
Here is another example, where I don't want the white dashed line (bit I've indicated with red line) to overlap the double yellow lines:

![image](https://user-images.githubusercontent.com/1386719/88585262-c76a2100-d04a-11ea-8b42-105ee92719bb.png)

**Comment by yackimoff** [comment]
This feature also could be useful when continuing a solid line with double dashed+solid. You want dashed part to the left or to the right of a single long solid line but now the solid line is broken as both parts are centered and have different widths.
