### ISSUE TITLE
Option to store colors on the color palette

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#72]
Currently the only way to store colors is to save a template.

I've ended up cloning the same template several times, once for each color (eg. white, red, green, blue). However, I often think of the template more as a line or fill style, which is independent of color.

Could we get ability to save colors on the color palette itself? Similar to how Network Skins 2 works?

This way I can have one template per line style, defining the most commonly used color for that line style, and then if I need to change color I can just open the color palette and click a stored color there. This will significantly reduce the number of templates I need.

**Comment by MacSergey** [comment]
Good idea, I'll add it to my plans

**Comment by BenjaminHoegh** [comment]
Could also be nice to have predefined colors of bus and bike lanes so we don't have to try to match it
