### ISSUE TITLE
Ability to manually add custom 'points' in/around the junction

### ISSUE THREAD

**Issue by aubergine10** [MacSergey/NodeMarkup#77]
Currently each lane division gets a point, and if we draw lines some additional poinrts appear where the lines intersect. This provides lots of flexibility, but there are still some situations in which we cannot draw lines or fills in the desired location.

Would it be possible to have a method by which additional points can be manually added in the vicinity of the junction?

A common case is T-junctions where I might want to draw (ie. _fill_) a yellow grid box in the middle. Currently it's difficult to achieve, particularly if it needs to be perfect square shape.

Pros:

- Much more line and fill flexibility because we can create custom points anywhere in vicinity of junction
- Ability to extend lines and fills in to the segments that enter the junction

Cons:

- Points would not update if the junction is altered (eg. with Move It mod); user would need to manually make adjustments if junction is changed (I don't think that's too much of a problem)

**Comment by MacSergey** [comment]
It can not be combined with the automatic redrawing the marking when a change of the intersection. Such a point will not have an unambiguous reference to something

**Comment by aubergine10** [comment]
Correct, the points will be static and user will have to alter the points if they alter the junction.

I still think advantages would outweigh the disadvantages.

**Comment by aubergine10** [comment]
Consider this junction, I want to add a yellow "keep junction clear" grid box in the middle where indicated.

![image](https://user-images.githubusercontent.com/1386719/88700389-8896a280-d100-11ea-82cd-361cb081fd80.png)

I can't move outer points (those with colored lines extending from them on the pic above) because they are being used to continue a solid white line around the bends at the junction.

With custom points, I could simply define points at the four corners where I want the box. A custom point could be visually different (eg. filled, or white) from auto-points.

**Comment by aubergine10** [comment]
I was able, with some careful fiddling of fill settings, to get something almost like a central box, but then I ran in to another problem: How do I get the outer borderline on this grid?

![image](https://user-images.githubusercontent.com/1386719/88700916-37d37980-d101-11ea-8863-0c2d1416c99d.png)

A yellow box decal is shown in that screenshot for comparison.

**Comment by MacSergey** [comment]
This breaks one of the main ideas of the mod-automatic rebuilding. I'm definitely not going to do something that requires manual movement. Use decals to do this
